name = "soc-roster-hub"
main = "src/index.js"
compatibility_date = "2026-07-29"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SOC_TOKENS"
id = "8e6c8d927d874a928d289792ee2a981b"

[[kv_namespaces]]
binding = "ADMIN_ALLOWLIST"
id = "18287c9b936e41acaef4bdef7e9a7a35"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "0b95ba4740b841508d0af264629277a3"


# All secrets managed via Cloudflare Dashboard → Worker → Settings → Variables & Secrets
